FROM node:22-slim AS web-builder

WORKDIR /app/frontend

COPY frontend/package.json frontend/package-lock.json /app/frontend/
RUN npm ci

COPY frontend /app/frontend
RUN npm run build

FROM node:22-slim

WORKDIR /app

COPY --from=web-builder /app/frontend/build /app/build
COPY --from=web-builder /app/frontend/node_modules /app/node_modules
COPY --from=web-builder /app/frontend/package.json /app/package.json

ENV NODE_ENV=production \
    PORT=3000 \
    HOST=0.0.0.0 \
    ORIGIN=http://localhost:8050

EXPOSE 3000

CMD ["node", "build"]
